### ISSUE TITLE
non-spherical mercator support as a goal

### ISSUE THREAD

**Issue by bradh** [ROGUE-JCTD/Grout#5]
If I understand your proposal, tiles are square in pixels, and in coordinate extent

How is that going to work with anything except spherical mercator?

**Comment by pepijnve** [comment]
What issue do you see here? If a tile is square in pixel coordinates and it's spatial extent is a square in spatial coordinates then the pixels are square in spatial coordinates as well. I don't see how this is restricted to web-mercator.

**Comment by bradh** [comment]
I couldn't see how the spatial extent would always be square in spatial coordinates. You are right that I should have pointed out examples like polar projections rather than anything-"not spherical mercator".

**Comment by pepijnve** [comment]
By spatial coordinates I mean the projected CS; not the underlying geographic CS. In polar stereo, or any other projected CS, you still have a cartesian system with an orthogonal easting northing axis. Why could you not define square tiles in that?

**Comment by antinodes** [comment]
I did the math before posting and double checked using qGIS (I wasn't convinced everything work "just work" either).  Using a Polar Azimuthal Equidistant projection the math all still works.  The units are all meters and the origin is at the pole.
